name: test-volume-adapter
on:
  pull_request
  issue_comment
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Chack keyword trigger
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@test-volume'
          reaction: rocket
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: 'json'
          fileOutput: 'json'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run changes files through test script
        run: |
          RUN_FILES=$(
            MODIFIED=${{ steps.file_changes.outputs.files_modified}} \
            ADDED=${{ steps.file_changes.outputs.files_added}} \
            node ${{ github.workspace }}/.github/workflows/getFileListVolumes.js
          )

          if [ "$RUN_FILES" = "[]" ] && [ steps.check.outputs.triggered == 'false' ]; then
            echo "No adapter files were modified"
            exit 0
          fi

          npm ci --omit=dev
          npm update @defillama/sdk

          for i in $(echo $RUN_FILES | tr  -d '"[]' | tr "," "\n")
          do 
            { 
              npm run test-dex ${i} 2>&1 | tee output.txt
              node ${{ github.workspace }}/.github/workflows/commentResultVolumes.js /home/runner/work/DefiLlama-Adapters/DefiLlama-Adapters/output.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
              if grep -q "\-\-\-\- ERROR \-\-\-\-" output.txt; then
                exit 1;
              fi
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done